In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
# import tensorflow_datasets as tfds

In [9]:
embedding_layer = layers.Embedding(1000, 4)

In [10]:
result = embedding_layer(tf.constant([1, 2, 3]))

In [11]:
print(result)

tf.Tensor(
[[ 0.02679456 -0.00762497  0.04970567  0.0030167 ]
 [ 0.00816674 -0.03682717 -0.02565083  0.00093832]
 [-0.03912232  0.04882419 -0.03158589 -0.03060891]], shape=(3, 4), dtype=float32)


In [33]:
import numpy as np
# define documents
docs = ['Well well done!','Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [34]:
t = tf.keras.preprocessing.text.Tokenizer()
a = t.fit_on_texts(docs)

In [35]:
t.texts_to_sequences(docs)

[[2, 2, 3],
 [4, 1],
 [7, 5],
 [8, 1],
 [9],
 [10],
 [6, 5],
 [11, 4],
 [6, 1],
 [12, 13, 3, 14]]

In [36]:
t.texts_to_matrix(docs)

array([[0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])